#!/usr/bin/env node
// hermes-g2-proxy: install and run the Hermes G2 proxy on the machine that runs Hermes Agent.
//
//   npx hermes-g2 setup              interactive wizard -> ~/.hermes-g2-proxy/.env
//   npx hermes-g2 run                start the proxy in the foreground
//   npx hermes-g2 service install    run at login/boot (systemd user unit, launchd agent, or a
//                                    Windows scheduled task); also: status | uninstall | logs
//   npx hermes-g2 doctor             re-check gateway, key, STT and print the URLs for the phone
//
// Node 22+ is required for live transcription (WebSocket client); Node 20 works for batch STT.

import { spawnSync, execFileSync } from 'node:child_process'
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync, unlinkSync } from 'node:fs'
import { homedir, networkInterfaces, platform, userInfo } from 'node:os'
import { dirname, resolve } from 'node:path'
import { createInterface } from 'node:readline/promises'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const SERVER = resolve(HERE, 'server.mjs')
const CONFIG_DIR = resolve(homedir(), '.hermes-g2-proxy')
const CONFIG_FILE = resolve(CONFIG_DIR, '.env')
const LOG_FILE = resolve(CONFIG_DIR, 'proxy.log')
const APP_DIR = resolve(CONFIG_DIR, 'app')
const SERVICE_NAME = 'hermes-g2-proxy'
const LAUNCHD_LABEL = 'com.hermesg2.proxy'
const TASK_NAME = 'Hermes G2 Proxy'

const [, , cmd = 'help', sub = ''] = process.argv

const c = {
  ok: s => `\x1b[32m✔\x1b[0m ${s}`,
  bad: s => `\x1b[31m✘\x1b[0m ${s}`,
  warn: s => `\x1b[33m!\x1b[0m ${s}`,
  dim: s => `\x1b[2m${s}\x1b[0m`,
  bold: s => `\x1b[1m${s}\x1b[0m`,
}

function readEnvFile(path) {
  const out = {}
  if (!existsSync(path)) return out
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    const m = /^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/.exec(line)
    if (m) out[m[1]] = m[2].replace(/^(['"])(.*)\1$/, '$2')
  }
  return out
}

function writeEnvFile(path, values) {
  mkdirSync(dirname(path), { recursive: true })
  const lines = [
    '# Hermes G2 proxy configuration (generated by `hermes-g2-proxy setup`)',
    `PORT=${values.PORT}`,
    `HOST=${values.HOST}`,
    `HERMES_URL=${values.HERMES_URL}`,
    `HERMES_API_KEY=${values.HERMES_API_KEY}`,
    '# Clients (the glasses app) must send this bearer key; defaults to HERMES_API_KEY',
    `PROXY_AUTH_KEY=${values.PROXY_AUTH_KEY || ''}`,
    `STT_PROVIDER=${values.STT_PROVIDER}`,
    `STT_API_KEY=${values.STT_API_KEY}`,
    `STT_MODEL=${values.STT_MODEL || ''}`,
    `STT_URL=${values.STT_URL || ''}`,
    `STT_LANGUAGE=${values.STT_LANGUAGE || ''}`,
    `CORS_ORIGIN=${values.CORS_ORIGIN || '*'}`,
    '',
  ]
  writeFileSync(path, lines.join('\n'), { mode: 0o600 })
}

/** Find the gateway key the way Hermes stores it: ~/.hermes/.env or a profile .env. */
function detectHermesKey() {
  const home = resolve(homedir(), '.hermes')
  const candidates = [resolve(home, '.env')]
  try {
    const profiles = resolve(home, 'profiles')
    if (existsSync(profiles)) for (const p of readdirSync(profiles)) candidates.push(resolve(profiles, p, '.env'))
  } catch {
    /* ignore */
  }
  for (const file of candidates) {
    const env = readEnvFile(file)
    if (env.API_SERVER_KEY) return { key: env.API_SERVER_KEY, file, port: env.API_SERVER_PORT, host: env.API_SERVER_HOST }
  }
  return null
}

async function fetchJson(url, init = {}, timeoutMs = 6000) {
  const res = await fetch(url, { ...init, signal: AbortSignal.timeout(timeoutMs) })
  let body = null
  try {
    body = await res.json()
  } catch {
    /* not json */
  }
  return { status: res.status, ok: res.ok, body }
}

async function checkHermes(url, key) {
  const results = []
  try {
    const h = await fetchJson(`${url}/health`)
    results.push(h.ok ? c.ok(`gateway reachable at ${url} (${h.body?.version ? `Hermes ${h.body.version}` : 'ok'})`) : c.bad(`gateway answered HTTP ${h.status} on /health`))
    if (!h.ok) return { ok: false, results }
  } catch (err) {
    results.push(c.bad(`cannot reach ${url}: ${err.cause?.code || err.message}`))
    return { ok: false, results }
  }
  try {
    const cap = await fetchJson(`${url}/v1/capabilities`, { headers: { Authorization: `Bearer ${key}` } })
    if (cap.ok) {
      const f = cap.body?.features || {}
      results.push(c.ok(`API key accepted · runs=${!!f.run_events_sse} approvals=${!!f.approval_events} steer=${!!f.run_steer}`))
      return { ok: true, results }
    }
    results.push(c.bad(cap.status === 401 || cap.status === 403 ? 'API key rejected (must match API_SERVER_KEY on the gateway)' : `capabilities HTTP ${cap.status}`))
    return { ok: false, results }
  } catch (err) {
    results.push(c.bad(`capabilities check failed: ${err.message}`))
    return { ok: false, results }
  }
}

async function checkStt(provider, key, url) {
  if (!key) return { ok: false, results: [c.warn('no STT key: voice input will not work until one is set')] }
  const base = (url || { deepgram: 'https://api.deepgram.com', elevenlabs: 'https://api.elevenlabs.io', openai: 'https://api.openai.com' }[provider] || '').replace(/\/+$/, '')
  const probe = {
    deepgram: [`${base}/v1/projects`, { Authorization: `Token ${key}` }],
    elevenlabs: [`${base}/v1/user`, { 'xi-api-key': key }],
    openai: [`${base}/v1/models`, { Authorization: `Bearer ${key}` }],
  }[provider]
  if (!probe) return { ok: false, results: [c.bad(`unknown provider ${provider}`)] }
  try {
    const r = await fetchJson(probe[0], { headers: probe[1] })
    if (r.ok) return { ok: true, results: [c.ok(`${provider} key accepted${provider === 'deepgram' ? ' (live transcription available)' : ' (batch transcription; no live preview)'}`)] }
    return { ok: false, results: [c.bad(`${provider} rejected the key (HTTP ${r.status})`)] }
  } catch (err) {
    return { ok: false, results: [c.bad(`${provider} unreachable: ${err.message}`)] }
  }
}

function addresses() {
  const out = []
  try {
    const ts = execFileSync(platform() === 'darwin' ? '/Applications/Tailscale.app/Contents/MacOS/Tailscale' : 'tailscale', ['ip', '-4'], { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim().split('\n')[0]
    if (ts) out.push({ kind: 'tailnet', ip: ts })
  } catch {
    /* no tailscale */
  }
  for (const [name, addrs] of Object.entries(networkInterfaces())) {
    for (const a of addrs || []) {
      if (a.family !== 'IPv4' || a.internal) continue
      if (a.address.startsWith('100.') && out.some(o => o.ip === a.address)) continue
      out.push({ kind: a.address.startsWith('100.') ? 'tailnet' : `lan (${name})`, ip: a.address })
    }
  }
  return out
}

/**
 * Prompt helper. Interactive on a TTY; when stdin is a pipe (scripted installs, tests) all lines
 * are read up front and consumed in order, because readline closes as soon as the pipe ends.
 */
let piped = null
async function makePrompter() {
  if (process.stdin.isTTY) {
    const rl = createInterface({ input: process.stdin, output: process.stdout })
    return { question: q => rl.question(q), close: () => rl.close() }
  }
  if (!piped) {
    const chunks = []
    for await (const chunk of process.stdin) chunks.push(chunk)
    piped = Buffer.concat(chunks).toString('utf8').split(/\r?\n/)
  }
  return {
    question: q => {
      process.stdout.write(q)
      const a = piped.length ? piped.shift() : ''
      process.stdout.write(`${a && !/key/i.test(q) ? a : a ? '••••' : ''}\n`)
      return Promise.resolve(a)
    },
    close: () => {},
  }
}

async function ask(rl, question, def, { secret = false } = {}) {
  const suffix = def ? c.dim(` [${secret ? '•'.repeat(Math.min(8, def.length)) + ' (keep)' : def}]`) : ''
  const answer = (await rl.question(`${question}${suffix}: `)).trim()
  return answer || def || ''
}

async function setup() {
  const rl = await makePrompter()
  const existing = readEnvFile(CONFIG_FILE)
  const detected = detectHermesKey()
  console.log(c.bold('\nHermes G2 proxy setup'))
  console.log(c.dim(`config: ${CONFIG_FILE}${Object.keys(existing).length ? ' (existing values shown as defaults)' : ''}\n`))

  const gwPort = detected?.port || '8642'
  const cfg = {}
  for (;;) {
    cfg.HERMES_URL = (await ask(rl, 'Hermes gateway URL (as seen from THIS machine)', existing.HERMES_URL || `http://127.0.0.1:${gwPort}`)).replace(/\/+$/, '')
    if (detected && !existing.HERMES_API_KEY) console.log(c.dim(`  found API_SERVER_KEY in ${detected.file}`))
    cfg.HERMES_API_KEY = await ask(rl, 'Hermes API key (API_SERVER_KEY)', existing.HERMES_API_KEY || detected?.key || '', { secret: true })
    const r = await checkHermes(cfg.HERMES_URL, cfg.HERMES_API_KEY)
    r.results.forEach(l => console.log('  ' + l))
    if (r.ok) break
    const again = (await rl.question('  Try again? [Y/n]: ')).trim().toLowerCase()
    if (again === 'n') break
  }

  for (;;) {
    cfg.STT_PROVIDER = (await ask(rl, 'Speech-to-text provider (deepgram = live preview; elevenlabs, openai = batch)', existing.STT_PROVIDER || 'deepgram')).toLowerCase()
    cfg.STT_API_KEY = await ask(rl, `${cfg.STT_PROVIDER} API key`, existing.STT_API_KEY || '', { secret: true })
    cfg.STT_LANGUAGE = await ask(rl, 'Language code (en, de, … blank = auto)', existing.STT_LANGUAGE || '')
    cfg.STT_MODEL = existing.STT_MODEL || ''
    cfg.STT_URL = existing.STT_URL || ''
    const r = await checkStt(cfg.STT_PROVIDER, cfg.STT_API_KEY, cfg.STT_URL)
    r.results.forEach(l => console.log('  ' + l))
    if (r.ok || !cfg.STT_API_KEY) break
    const again = (await rl.question('  Try again? [Y/n]: ')).trim().toLowerCase()
    if (again === 'n') break
  }

  cfg.PORT = await ask(rl, 'Port for the proxy', existing.PORT || '8643')
  cfg.HOST = await ask(rl, 'Bind address (0.0.0.0 = all interfaces)', existing.HOST || '0.0.0.0')
  cfg.PROXY_AUTH_KEY = existing.PROXY_AUTH_KEY || ''
  cfg.CORS_ORIGIN = existing.CORS_ORIGIN || '*'
  writeEnvFile(CONFIG_FILE, cfg)
  console.log(c.ok(`wrote ${CONFIG_FILE}`))

  printPhoneUrls(cfg)
  const svc = (await rl.question(`\nInstall as a ${serviceKind()} so it starts automatically? [Y/n]: `)).trim().toLowerCase()
  rl.close()
  if (svc !== 'n') await service('install')
  else console.log(`\nStart it with: ${c.bold('npx hermes-g2 run')}`)
}

function printPhoneUrls(cfg) {
  const port = cfg.PORT || '8643'
  console.log(c.bold('\nOn the phone (Hermes G2 settings page):'))
  const addrs = addresses()
  if (!addrs.length) console.log('  Hermes URL: http://<this-machine-ip>:' + port)
  for (const a of addrs) console.log(`  Hermes URL: http://${a.ip}:${port}   ${c.dim(a.kind)}`)
  console.log(`  API key:    the Hermes API key you entered above`)
  console.log(`  STT mode:   proxy`)
  console.log(c.dim('  Keep the proxy on a private network (LAN or tailnet); never expose it to the internet.'))
}

async function doctor() {
  const env = readEnvFile(CONFIG_FILE)
  if (!Object.keys(env).length) {
    console.log(c.bad(`no config at ${CONFIG_FILE}; run: npx hermes-g2 setup`))
    process.exitCode = 1
    return
  }
  console.log(c.bold('Hermes G2 proxy doctor'))
  console.log(c.dim(`config: ${CONFIG_FILE}`))
  const gw = await checkHermes(env.HERMES_URL, env.HERMES_API_KEY)
  gw.results.forEach(l => console.log('  ' + l))
  const stt = await checkStt(env.STT_PROVIDER, env.STT_API_KEY, env.STT_URL)
  stt.results.forEach(l => console.log('  ' + l))
  const major = Number(process.versions.node.split('.')[0])
  console.log('  ' + (major >= 22 ? c.ok(`Node ${process.versions.node}`) : c.warn(`Node ${process.versions.node}: live transcription needs Node 22+`)))
  try {
    const r = await fetchJson(`http://127.0.0.1:${env.PORT || 8643}/proxy/health`, {}, 3000)
    console.log('  ' + (r.ok ? c.ok(`proxy is running on port ${env.PORT || 8643} (hermes: ${r.body?.hermes}, stt: ${r.body?.stt})`) : c.warn(`proxy answered HTTP ${r.status}`)))
  } catch {
    console.log('  ' + c.warn(`proxy is not running on port ${env.PORT || 8643} (npx hermes-g2 run, or: service install)`))
  }
  printPhoneUrls(env)
}

function run() {
  if (existsSync(CONFIG_FILE) && !process.env.HERMES_G2_PROXY_ENV) process.env.HERMES_G2_PROXY_ENV = CONFIG_FILE
  return import(SERVER).then(m => m.start())
}

// ---- service management -------------------------------------------------------------------------

function serviceKind() {
  return { linux: 'systemd service', darwin: 'launchd agent', win32: 'Windows scheduled task' }[platform()] || 'service'
}

function nodeBin() {
  return process.execPath
}

/**
 * Services must not point into the npx cache (npm prunes it). Copy the proxy and its shared
 * modules into ~/.hermes-g2-proxy/app and run the service from there. Re-run `service install`
 * after upgrading to refresh the copy.
 */
function stagedServer() {
  return resolve(APP_DIR, 'proxy', 'server.mjs')
}
function stageApp() {
  const src = resolve(HERE, '..')
  for (const rel of ['proxy/server.mjs', 'proxy/ws-min.mjs', 'proxy/cli.mjs', 'shared/stt-providers.mjs', 'shared/stt-live.mjs', 'package.json']) {
    const from = resolve(src, rel)
    if (!existsSync(from)) throw new Error(`missing ${from}`)
    const to = resolve(APP_DIR, rel)
    mkdirSync(dirname(to), { recursive: true })
    copyFileSync(from, to)
  }
  return stagedServer()
}

function sh(cmd, args, opts = {}) {
  const r = spawnSync(cmd, args, { stdio: opts.quiet ? 'pipe' : 'inherit', shell: false })
  return r.status === 0
}

async function service(action) {
  const os = platform()
  if (!['install', 'uninstall', 'status', 'logs', 'show'].includes(action)) {
    console.log('usage: hermes-g2-proxy service install|uninstall|status|logs|show')
    return
  }
  if (action === 'install' && !existsSync(CONFIG_FILE)) {
    console.log(c.bad(`no config at ${CONFIG_FILE}; run setup first`))
    return
  }
  if (action !== 'show') mkdirSync(CONFIG_DIR, { recursive: true })
  if (action === 'install') console.log(c.ok(`copied the proxy to ${stageApp() === stagedServer() ? APP_DIR : APP_DIR}`))
  const target = process.env.HERMES_G2_SERVICE_OS || os // HERMES_G2_SERVICE_OS lets `show` preview another OS
  if (target === 'linux') return serviceLinux(action)
  if (target === 'darwin') return serviceMac(action)
  if (target === 'win32') return serviceWindows(action)
  console.log(c.warn(`no service integration for ${os}; run in the foreground with: npx hermes-g2 run`))
}

function linuxUnit(root) {
  return `[Unit]
Description=Hermes G2 proxy (CORS front door + STT relay for Hermes Agent)
After=network-online.target
Wants=network-online.target

[Service]
Environment=HERMES_G2_PROXY_ENV=${CONFIG_FILE}
ExecStart=${nodeBin()} ${stagedServer()}
Restart=always
RestartSec=3
${root ? `User=${userInfo().username}\n` : ''}
[Install]
WantedBy=${root ? 'multi-user.target' : 'default.target'}
`
}

function serviceLinux(action) {
  const root = typeof process.getuid === 'function' && process.getuid() === 0
  const unitDir = root ? '/etc/systemd/system' : resolve(homedir(), '.config/systemd/user')
  const unit = resolve(unitDir, `${SERVICE_NAME}.service`)
  const ctl = root ? ['systemctl'] : ['systemctl', '--user']
  if (action === 'show') {
    console.log(c.dim(`# ${unit}`))
    console.log(linuxUnit(root))
    console.log(c.dim(`# then: systemctl ${root ? '' : '--user '}daemon-reload && systemctl ${root ? '' : '--user '}enable --now ${SERVICE_NAME}${root ? '' : '\n#       sudo loginctl enable-linger $USER   (start at boot without a login session)'}`))
    return
  }
  if (action === 'install') {
    mkdirSync(unitDir, { recursive: true })
    writeFileSync(unit, linuxUnit(root))
    sh(ctl[0], [...ctl.slice(1), 'daemon-reload'])
    const ok = sh(ctl[0], [...ctl.slice(1), 'enable', '--now', SERVICE_NAME])
    console.log(ok ? c.ok(`installed and started ${unit}`) : c.bad('systemctl failed; see output above'))
    if (!root) {
      const linger = spawnSync('loginctl', ['enable-linger', userInfo().username], { stdio: 'pipe' })
      console.log(linger.status === 0 ? c.ok('login lingering enabled (starts at boot without a login session)') : c.warn('run `sudo loginctl enable-linger $USER` so the service also starts at boot without you logging in'))
    }
    console.log(c.dim(`logs: journalctl ${root ? '' : '--user '}-u ${SERVICE_NAME} -f`))
  } else if (action === 'uninstall') {
    sh(ctl[0], [...ctl.slice(1), 'disable', '--now', SERVICE_NAME], { quiet: true })
    if (existsSync(unit)) unlinkSync(unit)
    sh(ctl[0], [...ctl.slice(1), 'daemon-reload'], { quiet: true })
    console.log(c.ok('service removed'))
  } else if (action === 'status') sh(ctl[0], [...ctl.slice(1), 'status', '--no-pager', SERVICE_NAME])
  else sh('journalctl', [...(root ? [] : ['--user']), '-u', SERVICE_NAME, '-n', '100', '--no-pager'])
}

function macPlist() {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>${LAUNCHD_LABEL}</string>
  <key>ProgramArguments</key><array><string>${nodeBin()}</string><string>${stagedServer()}</string></array>
  <key>EnvironmentVariables</key><dict><key>HERMES_G2_PROXY_ENV</key><string>${CONFIG_FILE}</string></dict>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>${LOG_FILE}</string>
  <key>StandardErrorPath</key><string>${LOG_FILE}</string>
</dict></plist>
`
}

function serviceMac(action) {
  const plist = resolve(homedir(), 'Library/LaunchAgents', `${LAUNCHD_LABEL}.plist`)
  const domain = `gui/${typeof process.getuid === 'function' ? process.getuid() : 501}`
  if (action === 'show') {
    console.log(c.dim(`# ${plist}`))
    console.log(macPlist())
    console.log(c.dim(`# then: launchctl bootstrap ${domain} ${plist}`))
    return
  }
  if (action === 'install') {
    mkdirSync(dirname(plist), { recursive: true })
    writeFileSync(plist, macPlist())
    sh('launchctl', ['bootout', domain, plist], { quiet: true })
    const ok = sh('launchctl', ['bootstrap', domain, plist])
    console.log(ok ? c.ok(`installed and started ${plist}`) : c.bad('launchctl bootstrap failed; see output above'))
    console.log(c.dim(`logs: tail -f ${LOG_FILE}`))
  } else if (action === 'uninstall') {
    sh('launchctl', ['bootout', domain, plist], { quiet: true })
    if (existsSync(plist)) unlinkSync(plist)
    console.log(c.ok('launch agent removed'))
  } else if (action === 'status') sh('launchctl', ['print', `${domain}/${LAUNCHD_LABEL}`])
  else sh('tail', ['-n', '100', LOG_FILE])
}

function serviceWindows(action) {
  if (action === 'show') {
    console.log(c.dim(`# ${resolve(CONFIG_DIR, 'run-proxy.cmd')} (launched hidden via wscript by the scheduled task "${TASK_NAME}")`))
    console.log(`@echo off\nset HERMES_G2_PROXY_ENV=${CONFIG_FILE}\n"${nodeBin()}" "${stagedServer()}" >> "${LOG_FILE}" 2>&1`)
    console.log(c.dim(`# then: schtasks /Create /F /SC ONLOGON /TN "${TASK_NAME}" /TR "wscript.exe <run-proxy-hidden.vbs>" /RL LIMITED`))
    return
  }
  if (action === 'install') {
    const launcher = resolve(CONFIG_DIR, 'run-proxy.cmd')
    writeFileSync(launcher, `@echo off\r\nset HERMES_G2_PROXY_ENV=${CONFIG_FILE}\r\n"${nodeBin()}" "${stagedServer()}" >> "${LOG_FILE}" 2>&1\r\n`)
    const vbs = resolve(CONFIG_DIR, 'run-proxy-hidden.vbs')
    writeFileSync(vbs, `CreateObject("Wscript.Shell").Run """${launcher}""", 0, False\r\n`)
    const ok = sh('schtasks', ['/Create', '/F', '/SC', 'ONLOGON', '/TN', TASK_NAME, '/TR', `wscript.exe "${vbs}"`, '/RL', 'LIMITED'])
    if (ok) {
      sh('schtasks', ['/Run', '/TN', TASK_NAME], { quiet: true })
      console.log(c.ok(`scheduled task "${TASK_NAME}" runs the proxy at logon (hidden window); started now`))
      console.log(c.dim(`logs: ${LOG_FILE}`))
    } else console.log(c.bad('schtasks failed; see output above'))
  } else if (action === 'uninstall') {
    sh('schtasks', ['/End', '/TN', TASK_NAME], { quiet: true })
    sh('schtasks', ['/Delete', '/F', '/TN', TASK_NAME], { quiet: true })
    console.log(c.ok('scheduled task removed (a running proxy window, if any, must be closed by hand)'))
  } else if (action === 'status') sh('schtasks', ['/Query', '/TN', TASK_NAME, '/V', '/FO', 'LIST'])
  else if (existsSync(LOG_FILE)) console.log(readFileSync(LOG_FILE, 'utf8').split('\n').slice(-100).join('\n'))
}

function help() {
  console.log(`hermes-g2-proxy — the Hermes G2 proxy for the machine running Hermes Agent

  setup                  interactive wizard (writes ${CONFIG_FILE})
  run                    start the proxy in the foreground
  service install        start automatically (${serviceKind()}); copies the proxy to ${APP_DIR}
  service status|logs|uninstall|show   (show prints the unit/plist/task without installing)
  doctor                 check gateway, key, STT provider and print the URLs for the phone
`)
}

const main = { setup, run, doctor, help, service: () => service(sub) }[cmd]
if (!main) {
  console.log(c.bad(`unknown command "${cmd}"`))
  help()
  process.exitCode = 1
} else {
  Promise.resolve()
    .then(main)
    .catch(err => {
      console.error(c.bad(err.message))
      process.exitCode = 1
    })
}
